spring.application.name=hms-backend
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hms_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:hms_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Hms@12345}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET:CHANGE_ME_TO_A_LONG_RANDOM_SECRET_CHANGE_ME}
app.jwt.issuer=hms-backend
app.jwt.expiration-minutes=120

app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}

spring.jpa.open-in-view=false
spring.main.allow-bean-definition-overriding=true

